//TODO make dynamic id

export const SmartDevice = [
  {
    type: "SmartBulb",
    id: "1",
    name: "Lights",
    connectionState: "connected",
    icon: "fa-regular fa-lightbulb",
  },
  {
    type: "SmartOutlet",
    id: "2",
    name: "Electrics",
    connectionState: "connected",
    icon: "fa-solid fa-plug",
  },

  {
    type: "SmartTemperature",
    id: "3",
    name: "Temperature",
    connectionState: "poorConection",
    icon: "fa-solid fa-temperature-empty",
  },
];

export const SmartBulb = [
  {
    type: "bulb",
    id: "1",
    name: "Kitchen Lamp",
    connectionState: "connected",
    isTurnedOn: true,
    brightness: 77,
    color: "white",
    icon: "fa-regular fa-lightbulb",
  },
  {
    type: "bulb",
    id: "2",
    name: "Garage Lamp",
    connectionState: "poorConection",
    isTurnedOn: false,
    brightness: 0,
    color: "yellow",
    icon: "fa-regular fa-lightbulb",
  },
  {
    type: "bulb",
    id: "3",
    name: "Tarrace Lamp 1",
    connectionState: "connected",
    isTurnedOn: false,
    brightness: 0,
    color: "white",
    icon: "fa-regular fa-lightbulb",
  },
  {
    type: "bulb",
    id: "4",
    name: "Tarrace Lamp 2",
    connectionState: "connected",
    isTurnedOn: false,
    brightness: 0,
    color: "white",
    icon: "fa-regular fa-lightbulb",
  },
  {
    type: "bulb",
    id: "5",
    name: "Bedside Lamp",
    connectionState: "connected",
    isTurnedOn: true,
    brightness: 100,
    color: "white",
    icon: "fa-regular fa-lightbulb",
  },
  {
    type: "bulb",
    id: "6",
    name: "bathroom light",
    connectionState: "connected",
    isTurnedOn: true,
    brightness: 100,
    color: "white",
    icon: "fa-regular fa-lightbulb",
  },
  {
    type: "bulb",
    id: "7",
    name: "Bedroom Light",
    connectionState: "poorConection",
    isTurnedOn: false,
    brightness: 0,
    color: "white",
    icon: "fa-regular fa-lightbulb",
  },
  {
    type: "outside halogen",
    id: "8",
    name: "Kitchen Lamp",
    connectionState: "disconnected",
    isTurnedOn: true,
    brightness: 77,
    color: "white",
    icon: "fa-regular fa-lightbulb",
  },
];

export const SmartOutlet = [
  {
    type: "outlet",
    id: "1",
    name: "outlet 1A",
    connectionState: "connected",
    isTurnedOn: true,
    powerConsumption: 230,
    icon: "fa-solid fa-plug",
  },
  {
    type: "outlet",
    id: "2",
    name: "outlet 2A",
    connectionState: "connected",
    isTurnedOn: true,
    powerConsumption: 230,
    icon: "fa-solid fa-plug",
  },
  {
    type: "outlet",
    id: "3",
    name: "outlet 1B",
    connectionState: "Disconeccted",
    isTurnedOn: true,
    powerConsumption: 0,
    icon: "fa-solid fa-plug",
  },
  {
    type: "outlet",
    id: "4",
    name: "outlet 2B",
    connectionState: "Disconnected",
    isTurnedOn: true,
    powerConsumption: 0,
    icon: "fa-solid fa-plug",
  },
  {
    type: "outlet",
    id: "5",
    name: "outlet 3C",
    connectionState: "connected",
    isTurnedOn: true,
    powerConsumption: 230,
    icon: "fa-solid fa-plug",
  },
  {
    type: "outlet",
    id: "6",
    name: "outlet 3c",
    connectionState: "connected",
    isTurnedOn: true,
    powerConsumption: 400,
    icon: "fa-solid fa-plug",
  },
];

export const SmartTemperature = [
  {
    type: "temperatureSensor",
    id: "1",
    name: "outside Termometr",
    connectionState: "connected",
    temperature: 3,
    isTurnedOn: true,
    icon: "fa-solid fa-temperature-empty",
  },
  {
    type: "temperatureSensor",
    id: "2",
    name: "kitchen Termometr",
    connectionState: "connected",
    temperature: 22,
    isTurnedOn: true,
    icon: "fa-solid fa-temperature-empty",
  },
];
